name: CI

on:
  push:
    branches: [ master, 1.x ]
  pull_request:
    branches: [ master, 1.x ]
  workflow_dispatch:  # Add manual trigger capability

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test.yml@master
    with:
      os: 'ubuntu-latest'
      version: '22'  # Only test Node.js 22.x
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
